server:
  port: 8081

spring:
  # 数据源/数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sprinngbootmerge?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis配置
mybatis:
  type-aliases-package: com.springboot.merge.*.dto # 指向实体包路径
  mapper-locations: classpath*:/mapper/**/*.xml   # 指向mapper.xml文件的位置，模块名/mapper/*.xml

